mindmap
    Pengelolaan Parkir di Universitas
        Tujuan
            T1: Keamanan
            T2: Ketersediaan
            T3: Kenyamanan
        Masalah:
            MT1: Kantung parkir luas dan Terdisribusi-pengawasan sulit
            MT2: Keterbatasan lahan parkir, Tidak Optimal
            MT3: Aturan parkir
        Metrik:
            M1: Angka kehilangan 0 persen
            M2: Utilitas lahan parkir adalah 100%
            M3: Hak dan Kewajiban Pengguna Parkir
        Kerangka Solusi:
            KS3
                Pengguna Parkir-Radius lebih dari 2km?
                Pengencekan lahan parkir dilakukan terdistribusi pada kantung parkir
            KS1
                Security Officer di setiap lahan parkir 
                CCTV di setiap lahan parkir 
        Stakeholders:
            Dosen
            Mahasiswa
            Tenaga Kependidikan
            Tamu yang berkepentingan
            Pemilik Proyek

